# **Welcome! In this notebook, we'll solve Homework 3.10 together in Python.**

For this problem, we only need to import numpy. Let's start there.

In [1]:
import numpy as np

Now let's create an arbitrary $20 \times 30$ matrix. So that we can easily keep track of what numbers go where, let's fill it with the numbers $0$ to $599$ in order.

In [2]:
#np.arange(600) returns a giant array of numbers 0 to 599.
#Then, reshape(20,30) turns the array into a 20 by 30 matrix.
A = np.arange(600).reshape(20,30)

Let's look at this matrix and verify everything is correct.

In [3]:
A

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
         43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
         56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,
         73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,
         86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102,
        103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115,
        116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132,
        133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145,
        146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162,
        163, 164, 165, 166, 167, 168, 169, 170, 171,

Perhaps a bit cluttered and sloppy, but it looks just as we intended!

Now, numpy provides a great way to access submatrices.

We simply call:    `A[begin row (inclusive): end row (exclusive), begin column (inc): end column (exc)]`

This notation is not standard in base Python, but is consistent in numpy and worth getting comfortable with! This means part a of our homework can be executed in one line.

In [4]:
A[14:20,4:10]

array([[424, 425, 426, 427, 428, 429],
       [454, 455, 456, 457, 458, 459],
       [484, 485, 486, 487, 488, 489],
       [514, 515, 516, 517, 518, 519],
       [544, 545, 546, 547, 548, 549],
       [574, 575, 576, 577, 578, 579]])

We had to call these particular indices as our problem probably wanted a strictly inclusive range, while the second number of these ranges is exlusive. Also, we need to account for zero-based indexing, which is typically not assumed when given a problem description. If this is unclear, try comparing with the full matrix above and counting out rows and columns to find a manual solution! You'll see why these answers match pretty quickly.

Now let's make a matrix $B$ to insert into $A$ for part b.

We'll stick to making the entries sequential for clarity.

In [5]:
#With code similar to that for A:
B = np.arange(50).reshape(5,10)
B

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

Now, we use our knowledge of referencing submatrices of $A$ to very easily swap in our target matrix $B$!

In [6]:
#Reference the desired submatrix of A and set equal to B.
A[9:14,19:29] = B
A

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
         43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
         56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,
         73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,
         86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102,
        103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115,
        116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132,
        133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145,
        146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162,
        163, 164, 165, 166, 167, 168, 169, 170, 171,

It's a bit of a mess, but we can see where the low numbers of $B$ have been placed in $A$, and they're exactly where we want them!

For part c, we need to create a $50 \times 50$ matrix of the form $\begin{bmatrix}
A & 0\\
0 & A^T
\end{bmatrix}$.

We first create a zero matrix as a base. Our idea is to then insert a copy of $A$ and $A^T$ into our zero matrix at the right places, as we did above!

In [7]:
#Making a 50 x 50 zero matrix
B = np.zeros((50,50))
B

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

One more time, we make a matrix $A$ with sequential entries of the right size.

In [8]:
A = np.arange(625).reshape(25,25)
A

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,
         38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
         63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74],
       [ 75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
         88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124],
       [125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137,
        138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162,
        163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174],
      

This is what we wish to insert into $C$. So, let's do it!

In [9]:
#Set the top corner to A
B[0:25,0:25] = A

#Set the bottom corner to transpose(A)
B[25:50,25:50] = np.transpose(A)

#Examine our result
B

array([[  0.,   1.,   2., ...,   0.,   0.,   0.],
       [ 25.,  26.,  27., ...,   0.,   0.,   0.],
       [ 50.,  51.,  52., ...,   0.,   0.,   0.],
       ...,
       [  0.,   0.,   0., ..., 572., 597., 622.],
       [  0.,   0.,   0., ..., 573., 598., 623.],
       [  0.,   0.,   0., ..., 574., 599., 624.]])

The output is truncated due to how large a $50 \times 50$ matrix would be, but we can tell from this compact output that everything is as it should be! We're done with this problem!

***

Thanks for reading this week's first problem, and feel free to email me with any questions!

-Charles