# **Welcome! In this notebook, we'll solve Homework 3.11 together in Python.**

This is another problem where we only import numpy, so let's start with that!

In [1]:
import numpy as np

In this problem, we can only instantiate matrices with size below $32 \times 32$.

In order to work with $50 \times 50$ matrices as we require, let's choose to think of a $50 \times 50$ matrix $A$ as split into four $25 \times 25$ matrices:

$A = \begin{bmatrix}
A_1 & A_2\\
A_3 & A_4
\end{bmatrix}$

To start calculating, let's create two random $50 \times 50$ matrices $A$ and $B$ by describing their four smaller component matrices, which we can safely hold in memory. We'll fill these matrices with random integers between $0$ and $9$.

In [2]:
#Make a list to hold our randomly generated matrices.
smallerMatrices = []

#Generate!
for _ in range(8):
    smallerMatrices.append(np.random.randint(0,10,(25,25)))

Let's take a look at one of these and make sure it looks good.

In [3]:
smallerMatrices[0]

array([[7, 6, 8, 1, 4, 0, 7, 5, 3, 8, 6, 1, 8, 7, 7, 6, 1, 2, 7, 5, 1, 4,
        6, 8, 4],
       [5, 1, 8, 4, 5, 1, 1, 7, 6, 6, 5, 8, 9, 9, 8, 2, 3, 6, 1, 4, 3, 8,
        5, 6, 1],
       [0, 6, 2, 6, 0, 7, 3, 8, 8, 2, 6, 8, 4, 0, 7, 2, 4, 5, 5, 5, 3, 9,
        9, 4, 0],
       [1, 4, 6, 0, 8, 8, 1, 4, 7, 5, 1, 7, 1, 7, 5, 6, 0, 8, 7, 5, 5, 6,
        1, 4, 5],
       [1, 6, 8, 9, 7, 4, 5, 3, 9, 7, 2, 4, 9, 3, 1, 5, 0, 3, 5, 1, 7, 6,
        2, 5, 8],
       [2, 3, 4, 0, 6, 9, 3, 5, 5, 8, 8, 2, 3, 5, 9, 4, 0, 0, 1, 4, 0, 4,
        9, 6, 4],
       [8, 5, 2, 4, 1, 8, 4, 8, 4, 6, 6, 4, 7, 7, 7, 9, 3, 8, 4, 6, 9, 6,
        2, 5, 0],
       [0, 4, 0, 6, 3, 0, 1, 5, 1, 6, 8, 3, 0, 2, 7, 5, 5, 7, 2, 1, 6, 6,
        0, 1, 5],
       [1, 0, 2, 5, 1, 0, 1, 0, 4, 7, 7, 8, 4, 1, 1, 0, 4, 9, 2, 7, 3, 2,
        5, 6, 9],
       [4, 9, 7, 1, 5, 5, 6, 5, 0, 7, 3, 6, 4, 2, 2, 4, 0, 1, 2, 6, 5, 0,
        0, 8, 5],
       [9, 5, 1, 5, 7, 9, 5, 2, 9, 7, 9, 3, 3, 4, 4, 4, 4, 8, 4, 5, 7, 8,
      

Great! Let's next assign these common names for convenience as we go forward.

In [4]:
#Making better notation for ourselves!
A_1 = smallerMatrices[0]
A_2 = smallerMatrices[1]
A_3 = smallerMatrices[2]
A_4 = smallerMatrices[3]
B_1 = smallerMatrices[4]
B_2 = smallerMatrices[5]
B_3 = smallerMatrices[6]
B_4 = smallerMatrices[7]

As these matrices are small, we can do normal operations with them safely. Let's start with $A + B$, which we can easily find by directly adding each of the quadrants of $A$ to the corresponding quadrant of $B$.

In [5]:
AplusB_1 = A_1 + B_1
AplusB_2 = A_2 + B_2
AplusB_3 = A_3 + B_3
AplusB_4 = A_4 + B_4

Once again, let's peek and be sure this returned what we expect.

In [6]:
AplusB_1

array([[12, 14, 14,  4, 12,  5, 16, 10,  4, 12, 15,  9, 12, 11,  9, 15,
         9,  4, 12,  7,  6, 13,  6, 14, 10],
       [12,  6, 13, 11,  8,  6, 10, 14, 15, 12,  7, 13, 12, 18, 17,  7,
         7,  6,  9, 13,  6, 17, 14, 15,  4],
       [ 9,  6,  4,  7,  0, 15, 10, 10, 10,  2, 13,  8, 12,  0,  8, 11,
         7,  5,  7,  8,  3, 15, 18,  6,  2],
       [ 4,  7, 14,  9, 13, 15,  4,  5, 16,  7,  6, 15,  1, 12, 10, 14,
         4, 10, 15,  6,  9,  6,  2, 11, 14],
       [ 6, 12, 11, 10, 15,  8, 11,  9,  9, 12,  2,  7, 15, 11,  6, 10,
         7,  5, 14,  1,  7,  8, 10,  7,  9],
       [ 4,  4,  8,  8, 10, 13,  5,  8,  9, 14, 12,  7,  9, 11, 10, 13,
         7,  2,  4, 13,  6, 11,  9, 14, 12],
       [ 8,  6, 11, 13,  7, 10,  4, 13,  4, 13,  9, 12, 10, 14, 13,  9,
        10, 13,  7, 11, 16, 12,  4,  6,  3],
       [ 2,  4,  2, 14,  5,  6,  7, 11,  6,  8, 12,  9,  9,  9,  7, 11,
         5, 10,  6,  2, 12, 13,  4,  3,  9],
       [ 4,  2,  6,  8,  5,  8, 10,  6,  5, 11, 11, 10,  9,  3, 

Great! We did it. If we wanted to do further computations, we now have the four quadrants of $A + B$ fully descirbed and in memory, and could easily move forward in our analysis.

***

Next we compute $AB$.

Let's write these matrices in their block form and compute this smaller multiplication operation.

$AB = \begin{bmatrix}
A_1 & A_2\\
A_3 & A_4
\end{bmatrix} \begin{bmatrix}
B_1 & B_2\\
B_3 & B_4
\end{bmatrix} = \begin{bmatrix}
A_1B_1 + A_2B_3 & A_1B_2 + A_2B_4\\
A_3B_1 + A_4B_3 & A_3B_2 + A_4B_4
\end{bmatrix}$

All of these operations involve $25 \times 25$ matrices and so are safe to compute under our constraints!

Let's now compute each quadrant in our code.

In [7]:
#Computation using numpy methods to multiply matrices.
C_1 = np.matmul(A_1,B_1) + np.matmul(A_2,B_3)
C_2 = np.matmul(A_1,B_2) + np.matmul(A_2,B_4)
C_3 = np.matmul(A_3,B_1) + np.matmul(A_4,B_3)
C_4 = np.matmul(A_3,B_2) + np.matmul(A_4,B_4)

This may seem unintuitive at first - I recommend following the process of normal matrix multiplication and seeing row by row why this formula works! If you're unsure this is correct, we can luckily double check this answer against standard multiplication using a full $50 \times 50$ matrix.

In [8]:
#Making a 50 x 50 zero matrix
A = np.zeros((50,50))
B = np.zeros((50,50))

#Inserting each quadrant for both matrices
A[0:25,0:25] = A_1
A[0:25,25:] = A_2
A[25:,0:25] = A_3
A[25:,25:] = A_4

B[0:25,0:25] = B_1
B[0:25,25:] = B_2
B[25:,0:25] = B_3
B[25:,25:] = B_4

In [9]:
#Multiply our two matrices
C = np.matmul(A, B)

In [10]:
#Check each quadrant for equivalence of every element
[(C[0:25,0:25] == C_1).all(), (C[0:25,25:] == C_2).all(), (C[25:,0:25] == C_3).all(), (C[25:,25:] == C_4).all()]

[True, True, True, True]

So we've manually confirmed our formula works, and all four quadrants are the same! Wonderful!

***

Now, for the final problem, we have a complicated matrix setup. We first need to generate random and invertible $20 \times 20$ and $30 \times 30$ matrices. To do this, we will use $LU$ factorization - we will create a random $L$ and $U$ matrix for each!

In [11]:
#Fill a matrix with random entries.
randomMatrix = np.random.rand(20, 20)

#Use the lower and upper triangular parts of this matrix - filling in 0's elsewhere
L = np.tril(randomMatrix)
U = np.triu(randomMatrix)

#Our random 20 x 20 block is the product
A_11 = np.matmul(L,U)

We'll do the same for the $30 \times 30$ matrix.

In [12]:
randomMatrix = np.random.rand(30, 30)

#Our random 30 x 30 block is the product
A_22 = np.matmul(np.tril(randomMatrix),np.triu(randomMatrix))

We have no guarantees on $A_{21}$, so we make it a purely random $30 \times 20$ matrix, the exact size we need to fill.

In [13]:
A_21 = np.random.rand(30, 20)

Finally, we make our zero block.

In [14]:
A_12 = np.zeros((20,30))

One more chore - describe a $50 \times 1$ matrix $b$. For our problem and our constraints, we'll describe it in two parts, as a $20 \times 1$ top of $b$ and a $30 \times 1$ bottom of $b$.

In [15]:
topB = np.random.rand(20, 1)
botB = np.random.rand(30, 1)

Now, our goal is to break the system $Ax = b$ into parts, where $A = \begin{bmatrix}
A_{11} & 0\\
A_{21} & A_{22}
\end{bmatrix}$.

First, we can solve for the first $20$ entries of $x$ by only focusing on the $A_{11}$ block, as the adjacent block is all zeros.

In [16]:
#Solve easily using numpy's linalg.solve
topX = np.linalg.solve(A_11,topB)
topX

array([[-2605.74755515],
       [ 5928.66664913],
       [-7865.85662392],
       [-4297.02959056],
       [10686.07172773],
       [ -509.13439408],
       [ 1043.55591974],
       [ 1585.90478323],
       [-3932.0894406 ],
       [ 1315.11738677],
       [-1716.40990988],
       [  609.01216525],
       [ -225.25217583],
       [ -458.19925226],
       [  -49.54102991],
       [ 1303.26328659],
       [   40.60882991],
       [ -255.85698496],
       [   52.59381378],
       [  -33.52478423]])

Let's check for closeness that our multiplication works as it should! (Note usage of allclose, a method which allows for rounding imprecision, as these random values are likely to be quite messy.)

In [17]:
np.allclose(np.matmul(A_11, topX), topB)

True

So we've completely determined a large portion of the elements of $x$!

Now, we have to modify the bottom entries of $b$ based on our knowledge of the first entries of $x$.

That is, we can calculate the product $A_{21} \cdot topX$ and get a $30 \times 1$ matrix. Then, we can subtract this matrix from the bottom entries of $b$ to gain a new target vector that will allow us to solve the smaller system $A_{22} \cdot botX = botB - (A_{21} \cdot topX)$.

If this explanation appears unclear, my advice is again to write out the system of equations line by line, and solve one equation at a time until the pattern becomes clear! It's a subtle argument, with moving constants in specific ways, but a very good exercise in visualization and intuition in linear algebra.

In [18]:
#Calculate the constants to subtract from b
const = np.matmul(A_21, topX)

#Create a new b after subtraction
newBotB = botB - const

Now let's solve!

In [19]:
botX = np.linalg.solve(A_22,newBotB)

So we have a $topX$ and a $botX$ that together describe our desired solution!

Let's manually verify this solution by using numpy to solve the basic $50 \times 50$ system as a whole.

In [20]:
newBotB

array([[-1740.66435266],
       [  592.32610268],
       [-5216.18174332],
       [-3824.06918278],
       [ 1505.60298939],
       [ 2819.57967267],
       [-4268.92853528],
       [ 1240.80119652],
       [-3362.97043489],
       [  469.44799022],
       [-6468.59186731],
       [-4425.51547114],
       [-2794.06021094],
       [-5335.82211202],
       [ -571.56782537],
       [ 5409.41403526],
       [-1665.22607976],
       [-2417.18925263],
       [-2184.04289504],
       [-7720.00160882],
       [  191.41518102],
       [-8124.30272838],
       [ 3753.49385034],
       [ 3130.04682421],
       [-1396.43139994],
       [-7795.49617357],
       [-6712.4439153 ],
       [  675.49027382],
       [-3386.60414616],
       [ 4288.58699858]])

In [21]:
#Constructing each block of the large 50 x 50 matrix
A = np.zeros((50,50))
A[0:20,0:20] = A_11
A[0:20,20:] = A_12
A[20:,0:20] = A_21
A[20:,20:] = A_22

#Constructing b
B = np.zeros((50,1))
B[0:20] = topB
B[20:] = botB

#Constructing b
X = np.zeros((50,1))
X[0:20] = topX
X[20:] = botX

#Verifying closeness! We need a slight margin of error, as our values are very small and will
#sometimes be rounded to 0 as a datatype issue. This was the cause of much troubleshooting!
np.allclose(np.matmul(A, X), B, 1)

True

Fantastic! We've verified our output is very close - rounding errors will likely make an exact comparison return false, but all entries are close enough that our process is quite likely to be correct! On that happy note, we'll end this problem!

***

Thanks for reading this week's second problem, and as always, feel free to email me with any questions!

-Charles