# **Welcome! In this notebook, we'll solve Homework 3.22 together in Python.**

For this problem, we need to find an $LU$ factorization. We'll assume the matrices we work with have an $LU$ factorization exist - no random matrix inputs for us in this problem! We'll stick to the example from class to be sure everything works out.

In [1]:
import numpy as np

First, let's attempt to build a method manually to help us understand how $LU$ factorization works. Then, at the end, we'll examine how to use a premade method from the scipy library to do this efficiently in applications!

Let's begin by defining the matrix we'll work with, from Example 1 in section.

In [2]:
A = np.array([[1.,2.,3.],[2.,1.,3.],[4.,-1.,0.]])

Now, let's build an $LU$ factorization method. We'll make it a bit general, but will not use a $P$ matrix approach at the moment or check for existence.

Our general approach will be to start with $U$ as a copy of $A$ and $L$ as an identity matrix.

Then, an alternative way to view the steps we took in lecture are to view it as row operations in $U$, making $U$ slowly into an upper triangular matrix, and undoing those row operations in $L$, making $L$ slowly into a lower triangular matrix.

In [3]:
#We define a general LU factorization method.
def LU(A):
    
    #We assume our matrix is square, and find its size.
    size = A.shape[0]
    
    #U starts as a simple copy of A.
    #We copy so as not to modify the original object A.
    U = A.copy()
    
    #ID matrices are created with the np.eye(dimension) method.
    L = np.eye(size)
    
    #For each entry on the diagonal:
    for i in range(size):
            
        #Look at the entry on the diagonal in U.
        #Then, divide the column below by this entry.
        columnBelow = U[i+1:size, i] / U[i, i]
        
        #Row operation: subtract this column, multiplied by the i-th row of U.
        #np.newaxis just adds blank dimensions to make the multiplication work.
        U[i+1:size] -= columnBelow[0:size, np.newaxis] * U[i]
        
        #Place the column below into the L matrix, ensuring when multiplication is carried out,
        #we return to the original values in the matrix!
        L[i+1:, i] = columnBelow
        
        
    return L, U

This approach, and portions of the code block above, are modelled from [this page](https://johnfoster.pge.utexas.edu/numerical-methods-book/LinearAlgebra_LU.html), where the process behind this slightly different algorithmic approach is explained in more detail! For an in-depth explanation of the exact mathematics of this approach, known as Crout's algorithm, see [this paper.](http://www.it.uom.gr/teaching/linearalgebra/NumericalRecipiesInC/c2-3.pdf)

Now, let's run our method and verify it works.

In [4]:
L, U = LU(A)

In [5]:
L

array([[1., 0., 0.],
       [2., 1., 0.],
       [4., 3., 1.]])

In [6]:
U

array([[ 1.,  2.,  3.],
       [ 0., -3., -3.],
       [ 0.,  0., -3.]])

Our matrices are in the desired form! A good sign! Let's multiply them together now.

In [7]:
np.matmul(L,U)

array([[ 1.,  2.,  3.],
       [ 2.,  1.,  3.],
       [ 4., -1.,  0.]])

So, we've actually found an $LU$ decomposition of a permutation of our original matrix. This is subtle! On the bright side, this is enough for most of our needed applications. Modifying this algorithm to keep track of the permutations, and undo them if needed, is an exercise in storing memory of all our row computations - very feasible, but quite difficult to write clearly!

So, we'll call that good for our manual approach! Whew!

***

Now, let's import scipy, a library with many efficient factorizations built in. This will allow us to invoke a much more professional and efficient algorithm that also returns a $P$ matrix, meaning this will work with arbitrary matrices instead of our pure $LU$ factorization above.

In [8]:
#We only need one particular method from here
from scipy.linalg import lu

Let's redefine $A$ here, purely for the sake of our memory!

In [9]:
A = np.array([[1,2,3],[2,1,3],[4,-1,0]])

Now, in one line, let's factorize.

In [10]:
P, L, U = lu(A)

Let's look at our results! One thing to keep in mind is that in this algorithm, the factorization is written as $A = PLU$, so the $P$ matrix is not on the same side as we saw in lecture.

In [11]:
P

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [12]:
L

array([[1.        , 0.        , 0.        ],
       [0.25      , 1.        , 0.        ],
       [0.5       , 0.66666667, 1.        ]])

In [13]:
U

array([[ 4.  , -1.  ,  0.  ],
       [ 0.  ,  2.25,  3.  ],
       [ 0.  ,  0.  ,  1.  ]])

Looks good! Let's just quickly verify this multiplies to exactly what we want.

In [14]:
np.matmul(np.matmul(P,L),U)

array([[ 1.,  2.,  3.],
       [ 2.,  1.,  3.],
       [ 4., -1.,  0.]])

Exactly as we expected. Fantastic.

***

Thanks for reading this week's final problem! Email me with any questions!

-Charles